#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HowsTheWeather.Resource", IsApplication=true)]

namespace HowsTheWeather
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int sun_loader = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int weather_loading = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int imgItemWeather = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int imgMainWeather = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int lblForecastList = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int lblItemMax = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int lblItemMin = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int lblItemTime = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int lblItemWeather = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int lblMainCurrentLocation = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int lblMainDate = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int lblMainMessage = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int lblMainMinTemp = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int lblMainTemp = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int lblTheDayA = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int lblTheDayB = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int lblTheDayC = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int lblTheDayD = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int lblTheDayE = 2131099673;
			
			// aapt resource value: 0x7f06000e
			public const int lvForcastItemListA = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int lvForcastItemListB = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int lvForcastItemListC = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int lvForcastItemListD = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int lvForcastItemListE = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int rlA = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int rlB = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int rlC = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int rlD = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int rlE = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int forecast_item = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int dark_clouds_warm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dark_cloudy = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dark_fog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dark_light_storm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dark_lightning = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dark_partly_cloudy = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dark_rain = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dark_snow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dark_snow_storm = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dark_thunderstorm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int drizzle = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fog = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Icon = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Logo = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int mostly_sunny = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int mostly_sunny_dark = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int mostly_sunny_warm = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int mostly_sunny_warm_dark = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int overcast = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int partly_cloudy_warm = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int partly_sunny = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int rain = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int snow = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int sun_drizzle = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int sunny = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int sunny_hot = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int sunny_warm = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int warm_rain = 2130903067;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int afternoon_message = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int api_key = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int cloudy = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int error_location = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int evening_message = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int forecast_message = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int get_location = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int get_weather = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int heavyrain = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int loading_forecast = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int loading_location = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int loading_maxmin = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int loading_temp = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int morning_message = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int night_clear = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int overcast = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int partlysunny = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int permission_check = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int rainy = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int snowy = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int sunny = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int thunderstorm = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
